/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiteRouteImport } from './routes/suite'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as IndexRouteImport } from './routes/index'

const SuiteRoute = SuiteRouteImport.update({
  id: '/suite',
  path: '/suite',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/suite': typeof SuiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/suite': typeof SuiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/suite': typeof SuiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mobile' | '/suite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mobile' | '/suite'
  id: '__root__' | '/' | '/mobile' | '/suite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileRoute: typeof MobileRoute
  SuiteRoute: typeof SuiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suite': {
      id: '/suite'
      path: '/suite'
      fullPath: '/suite'
      preLoaderRoute: typeof SuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileRoute: MobileRoute,
  SuiteRoute: SuiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
