// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack.react-start'
import { supabase } from './client'

// Cache the token in a window-scoped variable to avoid calling getSession on every RPC.
// This keeps things fast in the browser while still allowing refresh when the token is missing.
const BROWSER_TOKEN_CACHE = typeof window !== 'undefined' ? (window as any).__supabase_cached_token : undefined;

export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined;

    try {
      if (typeof window !== 'undefined') {
        token = (window as any).__supabase_cached_token;
      }

      if (!token) {
        // Fallback: request the session once and cache the token
        const { data } = await supabase.auth.getSession();
        token = data.session?.access_token;
        if (token && typeof window !== 'undefined') (window as any).__supabase_cached_token = token;
      }
    } catch (err) {
      // If session reading fails, continue without token; server will respond with auth error if necessary
      console.warn('[attachSupabaseAuth] failed to read session', err);
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
)
