// This file is automatically generated. Do not edit it directly.
// Extended for Path B: Firebase Auth + Supabase database.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getFirebaseIdToken, isFirebaseConfigured } from '../firebase/client';

const SUPABASE_URL =
  (import.meta as any).env?.VITE_SUPABASE_URL ??
  (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);

const SUPABASE_PUBLISHABLE_KEY =
  (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY ??
  (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

const isBrowser = typeof window !== 'undefined';

/**
 * When Firebase Auth is configured (Path B), Supabase accepts the Firebase
 * ID token via accessToken. Requires Third-party Auth (Firebase) enabled in
 * Supabase Dashboard → Authentication → Third-party.
 *
 * Users must have custom claim role: 'authenticated' on their Firebase JWT.
 */
export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  ...(isFirebaseConfigured
    ? {
        accessToken: async () => {
          if (!isBrowser) return null;
          return (await getFirebaseIdToken(false)) ?? null;
        },
      }
    : {
        auth: {
          storage: isBrowser ? (localStorage as unknown as Storage) : undefined,
          persistSession: isBrowser,
          autoRefreshToken: isBrowser,
        },
      }),
});
